{{- if .Values.identity.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: identity
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-identity
  namespace: {{ .Release.Namespace | quote }} 
spec:
  selector:
    matchLabels:
      app: {{ template "reactioncommerce.name" . }}
      component: identity
      release: {{ .Release.Name }}
  replicas: {{ .Values.identity.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "reactioncommerce.name" . }}
        component: identity
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-identity
        image: "{{ .Values.identity.image.repository }}:{{ .Values.identity.image.tag }}"
        imagePullPolicy: {{ .Values.identity.image.pullPolicy }}
        ports:
          - name: identity
            containerPort: 4100
            protocol: TCP
        env:
        - name: API_URL
          value: {{ .Values.api.rootUrl }}/graphql
        - name: HYDRA_ADMIN_URL
          value: http://hydra.reaction.localhost:4445
        - name: HYDRA_TOKEN_URL
          value: http://hydra.reaction.localhost:4444/oauth2/token
        - name: LOG_LEVEL
          value: debug
        - name: METEOR_DISABLE_OPTIMISTIC_CACHING
          value: "1"
        - name: METEOR_WATCH_POLLING_INTERVAL_MS
          value: "10000"
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo.reaction.localhost:27017/local
        - name: MONGO_URL
          value: mongodb://mongo.reaction.localhost:27017/reaction
        - name: OAUTH2_CLIENT_DOMAINS
          value: {{ .Values.global.storeFrontUrl }}
        - name: PORT
          value: "4100"
        - name: ROOT_URL
          value: {{ .Values.identity.rootUrl }}
{{- end }}
